### ISSUE TITLE
Crash with version 1.2.0.338

### ISSUE THREAD

**Issue by Syer10** [Chicken-Bones/ForgeMultipart#328]
http://pastebin.com/xqncLyr0

**Comment by ate0ate** [comment]
I get the same crash using forge 1403 and EVERY multipart 1.2.0.XXX release so far...

**Comment by Chicken-Bones** [comment]
Hopefully fixed by 78560f53a3158c2a3ea04d6b5583bb3446547419 (1.2.0.339)

**Comment by ate0ate** [comment]
I can confirm this is fixed in builds 1.2.0.339 and 400. Thanks:)

**Comment by Haggle1996** [comment]
I am still experiencing this issue with 1.2.0.344, 341, 340, and 339. Using Forge 1403 and only when running a dedicated server. Works fine for SSP.

**Comment by Chicken-Bones** [comment]
crash log?
